language: node_js
node_js:
- '8'
before_install:
- echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
- npm install jsdoc publish-if-needed npm@latest -g
install:
- npm install
script:
- "./ci/build.js"
- "./ci/shim.js"
- "./ci/test.js"
after_success:
- publish-if-needed
env:
  global:
    secure: SSa4m6VkGGjTu5dTQYCwZGUZlE8QPERs/gqAbSmDwrcfvcLmmqoHYFTJlH/vamLVPrJMJbsBsdP6Ci0xf+L7U4HgPRcbS0gDtqS5yWKCxgJZEspySEKT10v4ffZQ8yPeH7I6NRWNmtGQ9Z8lqSeK/nmc6XhDUJ3o6OvjzSY8djTc0hPtXoEtqYpLI1ZetemnVqXg62ze3B6AYKSmfIzAKqQNyu0xi3VUYAbeFua1XJcyJLAvVE+8wY0zydFG7YJuLOL2YCM27oTIirZC9Gv3+K/GGZR0Q+Sa2+w/m5E18GhdX0XM28LIy2jJBRbtzm9y0s6Ht8hCbikRkbUh18RzUma/ipuo27TjW24mUC5WvfvZadzTJnpE5EGugXTrDQDEWZ1Rd4yqddbaYZ2rxQORYsm35t1hmqV4XQ1ITB8lDsjQQQxGQHUD9/HWCnxWhgkgCZmDuV4WQP+ngI9N6EyRzsuHx5vFQIDkOaglenQMqbF5S8oZ5gwURvYusTqhybqbHcB4Bw9Ey1jzTrmGVXLyZb2cXJktVr43L/TpY7UFOsiSUXcvZefztv2cmeuKN/Yomoy30T1JcUNOSMcjLqAadwUb6BJxJUEOt6uLAWq/+SjOMkPIPnnjCcmOSFNM2AL29/SPuQvo2G0Ss7u9DaYGvTJ5i11Sb3gIIXdku/PNyTo=
